name: Scheduled plot

on:
  schedule:
    - cron: 1 18 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1' # The R version to download (if necessary) and use.
  
      - uses: r-lib/actions/setup-r-dependencies@v1

      - uses: r-lib/actions/setup-renv@v2
      - run: Rscript -e 'print("hello")'

      - name: Set Date
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
